
# html lang
language: zh

# main menu navigation
menu:
  Home: /
  About: /about

# stylesheets loaded in the <head>
stylesheets:

stylesheets_preload:
- https://cdn.bootcss.com/highlight.js/9.6.0/styles/github.min.css # for highlight
- https://fonts.googleapis.com/css?family=Abril+Fatface&display=swap # for font

# scripts loaded in the end of the body
scripts_defer:
- https://cdn.bootcss.com/highlight.js/9.6.0/highlight.min.js # for highlight
- /js/paper.js # for basic script


social:
  Github: https://github.com/jiangege
  简历: https://jiangege.github.io/resume
  #Codepen: https://codepen.io/yours
  #Dribbble: https://dribbble.com/yours
  #Twitter: https://twitter.com/yours
  #知乎: https://www.zhihu.com/people/yours
  #掘金: https://juejin.im/user/yours
  #Mail: mailto:xxx@yourmail.xxxx
  # and more, you can add other link by the same way

# Uncomment to disable sidebar
# toc: false
# link: false
# archives: false
# categories: false
# tags: false

# theme color
main_color: default # forest | grass | sky | sun | sea

# google Analytics
google_analytics_id: xx-xxxxxxx-xx

# commend module
comment:
  enable: true
  appId: vO8Wf3bmuvpG2qrOgRNtBxmg-gzGzoHsz
  appKey: 9btreRIuQRXqfQCqvghrF4ql
  emojiCDN: https://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/
  placeholder: 留下你的骚话
  notify: false
  verify: false
  visitor: true
  avatar: retro
